import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Navbar />
        <div>
          <h1>Hello World</h1>
        </div>
        <Footer />
      </main>
    </div>
  );
}
